name: Generate UML Class Diagram from C# Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-uml:
    runs-on: ubuntu-latest  # Using an Ubuntu runner

    steps:
      - name: Checkout the repository code
        uses: actions/checkout@v2

      - name: Install Mono (to run NClass)
        run: |
          sudo apt-get update
          sudo apt-get install -y mono-complete

      - name: Download NClass (for UML generation)
        run: |
          wget https://github.com/nclass/nclass/releases/download/v3.0.0-beta4/nclass-3.0.0-beta4.zip
          unzip nclass-3.0.0-beta4.zip -d nclass
          chmod +x nclass/NClass.exe

      - name: Generate .puml from C# code using NClass
        run: |
          mono nclass/NClass.exe -generate-uml ./src -output ./generated -puml

      - name: Install PlantUML
        run: |
          sudo apt-get update
          sudo apt-get install -y plantuml  # Install PlantUML

      - name: Generate UML Diagram (PNG) from .puml
        run: |
          # Run PlantUML to generate PNG from the .puml file
          plantuml ./generated/*.puml  # Modify path if necessary

      - name: Upload UML diagram as artifact
        uses: actions/upload-artifact@v3
        with:
          name: uml-diagram
          path: ./generated/*.png  # Path to the generated UML image
